import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { loadRoomFixture } from './load-room-fixture.mjs';
globalThis.ProgressEvent ||= class {constructor(type,values){Object.assign(this,values);}};
const bytes=fs.readFileSync(new URL('../public/lookandsay/assets/local-bed/single-bed.glb',import.meta.url));
const length=bytes.readUInt32LE(12), json=JSON.parse(bytes.subarray(20,20+length));
json.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(28+length).toString('base64');
delete json.images;delete json.textures;
json.materials=json.materials.map(()=>({pbrMetallicRoughness:{}}));
const asset=await new GLTFLoader().parseAsync(JSON.stringify(json),'');
let triangles=0;
asset.scene.traverse(o=>{if(o.isMesh){triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;assert(Array.from(o.geometry.attributes.position.array).every(Number.isFinite));}});
assert(triangles<40000,'Bed has a bounded mesh budget');
const source=fs.readFileSync(new URL('../public/lookandsay/bedroom-refinement.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export async function','async function');
class Loader {async loadAsync(){return asset;}}
const old=THREE.TextureLoader.prototype.loadAsync;
THREE.TextureLoader.prototype.loadAsync=async()=>new THREE.Texture();
const refine=new Function('THREE','GLTFLoader','replaceRoomProps',source+';return refineBedroom;')(THREE,Loader,async()=>{});
const room=await loadRoomFixture();
const originals=['Cube.006','Cube.009','Cube.010','Plane.004','Plane.005','Plane.006'];
for(const name of originals)assert(room.getObjectByName(THREE.PropertyBinding.sanitizeNodeName(name)),`${name} exists before replacement`);
await refine(room);room.updateMatrixWorld(true);
assert.equal(room.getObjectByName('PlankFloor'),undefined,'Gapped floor removed');
const floor=room.getObjectByName('Continuous oak floor');
assert(floor,'Continuous floor installed');
const floorBounds=new THREE.Box3().setFromObject(floor,true);
assert(Math.abs(floorBounds.max.y-.27)<.00001,'Floor retains furniture contact elevation');
assert.equal(floor.geometry.type,'BoxGeometry','Floor has no open plank joints');
for(const name of originals)assert.equal(room.getObjectByName(THREE.PropertyBinding.sanitizeNodeName(name)),undefined,`${name} removed after replacement`);
const bed=room.getObjectByName('Detailed single bed');
const bounds=new THREE.Box3().setFromObject(bed,true);
assert(Math.abs(bounds.min.y-.27)<.001,'Bed touches the bedroom floor');
assert(Math.abs(bounds.max.x-bounds.min.x-2.1)<.001,'Bed length is 2.1m');
console.log('Bed bounds',bounds.min.toArray(),bounds.max.toArray());
const head=room.getObjectByName('Backdrop');
if(head)console.log('Headboard center',new THREE.Box3().setFromObject(head,true).getCenter(new THREE.Vector3()).toArray());
THREE.TextureLoader.prototype.loadAsync=old;
const html=fs.readFileSync(new URL('../public/lookandsay/index.html',import.meta.url),'utf8');
assert(html.includes("canvas.addEventListener('pointermove'"));
assert(!html.includes('camera.rotation.y = Math.sin'));
assert(html.includes("renderer.xr.isPresenting || !document.body.classList.contains('exploring')"));
console.log('PASS:',triangles,'bed triangles, floor contact, life-size placement, browser look controls');
