import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import * as THREE from 'three';
const source=readFileSync(new URL('../public/mriprep/index.html',import.meta.url),'utf8');
function fn(name){const start=source.indexOf(`  function ${name}(`);assert.ok(start>=0,name);return source.slice(start,source.indexOf('\n  }',start)+4);}
function scope(names,values){const c=vm.createContext({THREE,performance:{now:()=>10000},...values});vm.runInContext(names.map(fn).join('\n'),c);return c;}
const motion=()=>({tableMoving:true,tableTarget:1,tableTravel:.45,buddySeq:{phase:'in'},stillRunning:true,moveT:.2,moveTo:{},waitForReveal:true,wallTarget:1,wallNow:.3,fadeJob:{},veil:{material:{opacity:1}}});
test('Stop freezes all motion and cancels pending fade commits',()=>{const c=scope(['stopMotion'],motion());c.stopMotion();assert.equal(c.tableTarget,.45);assert.equal(c.tableMoving,false);assert.equal(c.stillRunning,false);assert.equal(c.buddySeq,null);assert.equal(c.wallTarget,.3);assert.equal(c.fadeJob,null);assert.equal(c.moveT,1);});
test('Fade changes position only behind an opaque cover, then rearms dwell',()=>{let committed=0,settled=0;const c=scope(['transitionTo','updateFade'],{fadeJob:null,veil:{position:new THREE.Vector3(),material:{opacity:0}},renderer:{xr:{isPresenting:false}},camera:{getWorldPosition:()=>{}},settleInput:()=>settled++,lastLayout:null});c.transitionTo(()=>committed++);c.updateFade(.3);assert.equal(committed,0);c.updateFade(.16);assert.equal(committed,1);assert.equal(c.veil.material.opacity,1);c.updateFade(.8);assert.equal(committed,1);assert.equal(settled,1);assert.equal(c.fadeJob,null);});
test('Slide out retains current travel until the chosen transition executes',()=>{let called=0;const c=scope(['slideOut'],{tableTravel:.85,tableTarget:.85,stillRunning:true,starPanel:{visible:true},stage:'still',stageNameEl:{},STAGE_LABEL:{table:'Table'},startTableMove:()=>called++});c.slideOut();assert.equal(c.tableTravel,.85);assert.equal(c.tableTarget,0);assert.equal(c.stage,'table');assert.equal(c.stillRunning,false);assert.equal(called,1);});
function gazeScope(){let hits=[],picks=0;const button={material:{},userData:{label:'Continue',cold:{},hot:{},progress:{value:0},pick:()=>picks++}};const cam={getWorldPosition:()=>{},getWorldDirection:()=>{}};const c=scope(['setHot','updateGaze'],{renderer:{xr:{isPresenting:true,getCamera:()=>cam}},camera:cam,raycaster:{ray:{origin:{},direction:{}},intersectObjects:()=>hits},uiButtons:[button],hot:null,dwellMs:0,reticle:{style:{}},reticleFg:{style:{}},awayMs:0,needsLookAway:true,arrivalUntil:11800,paused:false,stopReady:true,prefs:{dwell:1000},firedSafety:null,motionBusy:()=>false});return {c,button,look:(b)=>hits=b?[{object:b}]:[],picks:()=>picks};}
test('Headset dwell cannot trigger on arrival; requires looking away and a fresh dwell',()=>{const g=gazeScope();g.look(g.button);for(let i=0;i<60;i++)g.c.updateGaze(.05);assert.equal(g.picks(),0);g.c.arrivalUntil=0;g.look(null);for(let i=0;i<7;i++)g.c.updateGaze(.05);g.look(g.button);for(let i=0;i<20;i++)g.c.updateGaze(.05);assert.equal(g.picks(),1);for(let i=0;i<40;i++)g.c.updateGaze(.05);assert.equal(g.picks(),1);});
test('Stop bypasses arrival and movement lock, but cannot repeatedly activate while stared at',()=>{const g=gazeScope();g.button.userData.label='Stop';g.button.userData.safety=true;g.c.motionBusy=()=>true;g.look(g.button);for(let i=0;i<30;i++)g.c.updateGaze(.05);assert.equal(g.picks(),1);});
test('Dwell surface fill resets when focus changes without changing button size',()=>{const g=gazeScope();g.c.arrivalUntil=0;g.c.needsLookAway=false;g.look(g.button);for(let i=0;i<10;i++)g.c.updateGaze(.05);assert.equal(g.button.userData.progress.value,.5);g.look(null);g.c.updateGaze(.05);assert.equal(g.button.userData.progress.value,0);});
test('UI layout is headset-relative, spaced apart and at least 1.8m away',()=>{const world=new THREE.Group();world.position.set(0,0,7);world.updateMatrixWorld(true);const buttons=Array.from({length:9},()=>new THREE.Mesh(new THREE.PlaneGeometry(.52,.203)));world.add(...buttons);const c=scope(['placeArc'],{renderer:{xr:{isPresenting:false}},camera:{getWorldPosition:p=>p.set(.3,1.7,.2)},stage:'visit',buddySeq:null,worldRoot:world,uiButtons:buttons,textPanel:null});c.placeArc(new THREE.Vector3(),new THREE.Vector3(0,0,-1),{radius:1.8});assert.ok(buttons[0].position.distanceTo(buttons[1].position)>.6);assert.ok(buttons[0].position.distanceTo(buttons[3].position)>.3);assert.equal(buttons[0].position.y,1.68);assert.ok(Math.abs(buttons[0].position.z+8.6)<.00001);world.updateMatrixWorld(true);const normal=buttons[0].getWorldDirection(new THREE.Vector3());const towardEye=new THREE.Vector3(.3,1.7,.2).sub(buttons[0].getWorldPosition(new THREE.Vector3())).normalize();assert.ok(normal.dot(towardEye)>.999);});
test('Finish never waits for the scanner or claims unperformed activities',()=>{const done=source.slice(source.indexOf('    done() {'),source.indexOf('  /* ── Per-stage'));assert.doesNotMatch(done,/goTo\(|heard|held still|earned/);assert.match(done,/Explore again/);assert.match(done,/Exit VR/);assert.match(fn('setStage'),/\['bedroom','sounds','done'\]/);});
test('Startup waits for the bedroom; no timed load bypass remains',()=>{assert.doesNotMatch(source,/Promise\.race/);assert.match(source,/const suiteReady = roomReady\.then/);assert.match(fn('beginExperience'),/!roomLoaded/);assert.match(source,/id="startBtn" disabled/);});

test('Stop requires a fresh look when a new menu appears beneath the gaze',()=>{const g=gazeScope();g.c.stopReady=false;g.button.userData.label='Stop';g.button.userData.safety=true;g.look(g.button);for(let i=0;i<40;i++)g.c.updateGaze(.05);assert.equal(g.picks(),0);g.look(null);g.c.updateGaze(.05);g.look(g.button);for(let i=0;i<8;i++)g.c.updateGaze(.05);assert.equal(g.picks(),1);});

test('Muted scanner gain remains zero and its level is retained',()=>{let gain;const c=scope(['applyVolume'],{prefs:{muted:true},volStep:2,savePrefs:()=>{},wakeAudio:()=>{},paused:false,soundsOn:true,VOL_STEPS:[.08,.16,.28,.4],master:{gain:{value:.1,cancelScheduledValues:()=>{},setValueAtTime:()=>{},linearRampToValueAtTime:v=>gain=v}},audioCtx:{currentTime:1}});c.applyVolume();assert.equal(gain,0);assert.equal(c.prefs.scanner,2);});
test('Finishing during scanner preparation cancels the pending stage change',async()=>{
  let resolve;const ready=new Promise(r=>resolve=r);const entered=[];
  const c=scope(['setStage'],{stageRequest:0,suiteLoaded:false,loadingScanner:false,suiteReady:ready,showCaption:()=>{},stopMotion:()=>{},settingsOpen:false,paused:false,stage:'bedroom',stageNameEl:{},STAGE_LABEL:{done:'Done'},STAGES:{done:()=>entered.push('done'),visit:()=>entered.push('visit')},faceAnchor:()=>{}});
  c.setStage('visit');assert.equal(c.loadingScanner,true);c.setStage('done');c.suiteLoaded=true;resolve();await ready;await Promise.resolve();assert.deepEqual(entered,['done']);assert.equal(c.stage,'done');
});
